from pathlib import Path
from datetime import datetime, timezone
import json
import logging
import shutil
import subprocess
import sys
import time


# ============================================================
# PATHS
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

INGESTION_DIR = BASE_DIR / "ingestion"

RAW_DIR = BASE_DIR / "data" / "raw"
NEW_STRUCTURED_DIR = BASE_DIR / "data" / "new_structured"
BASELINE_DIR = BASE_DIR / "data" / "structured_final"

COMPARISON_DIR = BASE_DIR / "data" / "comparison"
CHANGES_FILE = COMPARISON_DIR / "changes.json"

MANIFEST_FILE = BASE_DIR / "data" / "content_manifest.json"

PIPELINE_LOG_DIR = BASE_DIR / "data" / "pipeline_logs"


# ============================================================
# PIPELINE CONFIGURATION
# ============================================================

PIPELINE_NAME = "consiva-ingestion-pipeline"

STAGES = [
    "scraping",
    "cleaning",
    "comparison",
    "vector_update",
    "manifest_update",
    "baseline_promotion",
]


# ============================================================
# LOGGING
# ============================================================

PIPELINE_LOG_DIR.mkdir(
    parents=True,
    exist_ok=True
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(
            PIPELINE_LOG_DIR / "pipeline.log",
            encoding="utf-8"
        )
    ]
)

logger = logging.getLogger(__name__)


# ============================================================
# UTILITIES
# ============================================================

def utc_now() -> str:
    """Return current UTC timestamp."""

    return datetime.now(timezone.utc).isoformat()


def run_stage(stage_name: str, script_name: str) -> None:
    """
    Execute one ingestion stage as a subprocess.

    Each stage remains independently executable and testable.
    """

    logger.info("=" * 70)
    logger.info(f"STARTING STAGE: {stage_name.upper()}")
    logger.info("=" * 70)

    script_path = INGESTION_DIR / script_name

    if not script_path.exists():
        raise FileNotFoundError(
            f"Required stage script not found: {script_path}"
        )

    start_time = time.time()

    result = subprocess.run(
        [
            sys.executable,
            str(script_path)
        ],
        cwd=BASE_DIR,
        capture_output=True,
        text=True
    )

    duration = time.time() - start_time

    # --------------------------------------------------------
    # Forward stage output into pipeline logs
    # --------------------------------------------------------

    if result.stdout:
        for line in result.stdout.splitlines():
            logger.info(f"[{stage_name}] {line}")

    if result.stderr:
        for line in result.stderr.splitlines():
            logger.error(f"[{stage_name}] {line}")

    # --------------------------------------------------------
    # Check result
    # --------------------------------------------------------

    if result.returncode != 0:

        logger.error(
            f"STAGE FAILED: {stage_name} "
            f"(exit code={result.returncode}, "
            f"duration={duration:.2f}s)"
        )

        raise RuntimeError(
            f"Pipeline stage '{stage_name}' failed."
        )

    logger.info(
        f"STAGE COMPLETED: {stage_name} "
        f"({duration:.2f}s)"
    )


# ============================================================
# VALIDATION
# ============================================================

def validate_pipeline_directories() -> None:
    """Validate required project directories."""

    logger.info("Validating pipeline directories...")

    required_directories = [
        BASE_DIR,
        INGESTION_DIR,
        RAW_DIR,
        NEW_STRUCTURED_DIR,
        BASELINE_DIR,
        COMPARISON_DIR,
    ]

    for directory in required_directories:

        if not directory.exists():

            # These directories can safely be created.
            directory.mkdir(
                parents=True,
                exist_ok=True
            )

            logger.info(
                f"Created directory: {directory}"
            )

    logger.info("Directory validation completed.")


# ============================================================
# CHANGE FILE VALIDATION
# ============================================================

def load_changes() -> dict:
    """
    Load changes.json generated by compare.py.

    This file determines what should be processed.
    """

    if not CHANGES_FILE.exists():

        raise FileNotFoundError(
            f"Comparison file not found: {CHANGES_FILE}"
        )

    try:

        with open(
            CHANGES_FILE,
            "r",
            encoding="utf-8"
        ) as file:

            changes = json.load(file)

    except json.JSONDecodeError as error:

        raise ValueError(
            f"Invalid changes.json: {error}"
        )

    if not isinstance(changes, dict):

        raise ValueError(
            "changes.json must contain a JSON object."
        )

    return changes


# ============================================================
# CHANGE SUMMARY
# ============================================================

def extract_change_summary(changes: dict) -> dict:
    """
    Extract NEW / CHANGED / UNCHANGED / DELETED information
    from the current compare.py output structure.
    """

    summary = {
        "new": [],
        "changed": [],
        "unchanged": [],
        "deleted": [],
    }

    # Current compare.py structure:
    #
    # {
    #   "summary": {
    #       "new": 0,
    #       "changed": 2,
    #       "unchanged": 37,
    #       "deleted": 0
    #   },
    #   "pages": {
    #       "new": [...],
    #       "changed": [...],
    #       "unchanged": [...],
    #       "deleted": [...]
    #   }
    # }

    pages = changes.get("pages", {})

    if not isinstance(pages, dict):
        raise ValueError(
            "Invalid changes.json: 'pages' must be an object."
        )

    for status in summary:

        value = pages.get(status, [])

        if isinstance(value, list):
            summary[status] = value

    return summary

# ============================================================
# BUILD MANIFEST UPDATE
# ============================================================

def get_successful_page_paths(
    change_summary: dict
) -> list[Path]:
    """
    Convert NEW and CHANGED entries into actual files inside
    new_structured.

    This function is used only after vector DB success.
    """

    successful_pages = []

    for status in ("new", "changed"):

        for item in change_summary[status]:

            # ------------------------------------------------
            # Handle dictionary-based compare output
            # ------------------------------------------------

            if isinstance(item, dict):

                filename = (
                    item.get("file_name")
                    or item.get("filename")
                    or item.get("page")
                )

            # ------------------------------------------------
            # Handle string-based compare output
            # ------------------------------------------------

            elif isinstance(item, str):

                filename = item

            else:

                continue

            if not filename:
                continue

            # Root homepage special filename generated by master_clean.py
            if filename == "consiva.ai":
                filename = "consiva.ai_.txt"
            elif not filename.endswith(".txt"):
                filename = f"{filename}.txt"

            file_path = NEW_STRUCTURED_DIR / filename

            if not file_path.exists():

                logger.warning(
                    f"Changed page file not found: {file_path}"
                )

                continue

            successful_pages.append(file_path)

    return successful_pages


# ============================================================
# EXTRACT DELETED PAGE IDS
# ============================================================

def get_deleted_page_ids(
    change_summary: dict
) -> list[str]:
    """
    Extract page IDs for deleted pages.

    Supports dictionary and string compare entries.
    """

    deleted_ids = []

    for item in change_summary["deleted"]:

        if isinstance(item, dict):

            page_id = (
                item.get("page_id")
                or item.get("id")
                or item.get("filename")
                or item.get("file_name")
            )

        elif isinstance(item, str):

            page_id = item

        else:

            continue

        if page_id:

            # Remove .txt if present.
            if page_id.endswith(".txt"):
                page_id = Path(page_id).stem

            deleted_ids.append(page_id)

    return deleted_ids


# ============================================================
# UPDATE MANIFEST
# ============================================================

def update_manifest(
    successful_pages: list[Path],
    deleted_page_ids: list[str]
) -> None:
    """
    Update manifest only after Vector DB update succeeds.

    Imports manifest.py rather than duplicating manifest logic.
    """

    logger.info("=" * 70)
    logger.info("UPDATING MANIFEST")
    logger.info("=" * 70)

    sys.path.insert(
        0,
        str(BASE_DIR)
    )

    from ingestion.manifest import apply_changes

    apply_changes(
        successful_pages=successful_pages,
        deleted_page_ids=deleted_page_ids
    )

    logger.info("Manifest update completed successfully.")


# ============================================================
# BASELINE PROMOTION
# ============================================================

def promote_baseline() -> None:
    """
    Promote new_structured to structured_final.

    This happens only after Vector DB and manifest updates
    have succeeded.
    """

    logger.info("=" * 70)
    logger.info("PROMOTING BASELINE")
    logger.info("=" * 70)

    from ingestion.promote import promote_baseline as promote

    promote()

    logger.info(
        "Baseline promotion completed successfully."
    )


# ============================================================
# PIPELINE STATUS
# ============================================================

def create_pipeline_status(
    status: str,
    started_at: str,
    completed_at: str | None = None,
    failed_stage: str | None = None,
    error: str | None = None,
    changes: dict | None = None
) -> dict:
    """
    Create a structured pipeline execution status.

    This can later be sent to:
    - Cloud Logging
    - monitoring systems
    - Slack/email alerts
    - dashboards
    - databases
    """

    return {
        "pipeline": PIPELINE_NAME,
        "status": status,
        "started_at": started_at,
        "completed_at": completed_at,
        "failed_stage": failed_stage,
        "error": error,
        "changes": changes or {},
    }


# ============================================================
# SAVE PIPELINE STATUS
# ============================================================

def save_pipeline_status(status: dict) -> None:
    """Save execution status for monitoring/debugging."""

    status_file = (
        PIPELINE_LOG_DIR /
        "latest_run.json"
    )

    temp_file = (
        PIPELINE_LOG_DIR /
        "latest_run.tmp"
    )

    with open(
        temp_file,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            status,
            file,
            ensure_ascii=False,
            indent=2
        )

        file.flush()
       

    # Atomic replacement.
    temp_file.replace(status_file)


# ============================================================
# MAIN PIPELINE
# ============================================================

def run_pipeline() -> None:
    """Execute the complete ingestion pipeline."""

    pipeline_start = utc_now()
    start_time = time.time()

    current_stage = None

    logger.info("")
    logger.info("#" * 70)
    logger.info(f"STARTING {PIPELINE_NAME.upper()}")
    logger.info(f"Started at: {pipeline_start}")
    logger.info("#" * 70)

    try:

        # ----------------------------------------------------
        # 0. Validate environment
        # ----------------------------------------------------

        current_stage = "validation"

        validate_pipeline_directories()

        # ----------------------------------------------------
        # 1. SCRAPE
        # ----------------------------------------------------

        current_stage = "scraping"

        run_stage(
            stage_name="scraping",
            script_name="scraper.py"
        )

        # ----------------------------------------------------
        # 2. CLEAN
        # ----------------------------------------------------

        current_stage = "cleaning"

        run_stage(
            stage_name="cleaning",
            script_name="master_clean.py"
        )

        # ----------------------------------------------------
        # 3. COMPARE
        # ----------------------------------------------------

        current_stage = "comparison"

        run_stage(
            stage_name="comparison",
            script_name="compare.py"
        )

        # ----------------------------------------------------
        # 4. LOAD CHANGES
        # ----------------------------------------------------

        changes = load_changes()

        change_summary = extract_change_summary(
            changes
        )

        logger.info(
            "Change summary | "
            f"NEW={len(change_summary['new'])}, "
            f"CHANGED={len(change_summary['changed'])}, "
            f"UNCHANGED={len(change_summary['unchanged'])}, "
            f"DELETED={len(change_summary['deleted'])}"
        )

        # ----------------------------------------------------
        # 5. VECTOR DB UPDATE
        # ----------------------------------------------------

        current_stage = "vector_update"

        run_stage(
            stage_name="vector_update",
            script_name="vector_updater.py"
        )

        # ----------------------------------------------------
        # IMPORTANT:
        #
        # Everything below this point happens only when the
        # vector updater exits successfully.
        # ----------------------------------------------------

        successful_pages = get_successful_page_paths(
            change_summary
        )

        deleted_page_ids = get_deleted_page_ids(
            change_summary
        )

        # ----------------------------------------------------
        # 6. MANIFEST UPDATE
        # ----------------------------------------------------

        current_stage = "manifest_update"

        update_manifest(
            successful_pages=successful_pages,
            deleted_page_ids=deleted_page_ids
        )

        # ----------------------------------------------------
        # 7. BASELINE PROMOTION
        # ----------------------------------------------------

        current_stage = "baseline_promotion"

        promote_baseline()

        # ----------------------------------------------------
        # SUCCESS
        # ----------------------------------------------------

        completed_at = utc_now()

        duration = time.time() - start_time

        status = create_pipeline_status(
            status="success",
            started_at=pipeline_start,
            completed_at=completed_at,
            changes={
                "new": len(change_summary["new"]),
                "changed": len(change_summary["changed"]),
                "unchanged": len(change_summary["unchanged"]),
                "deleted": len(change_summary["deleted"]),
            }
        )

        save_pipeline_status(status)

        logger.info("")
        logger.info("#" * 70)
        logger.info("PIPELINE COMPLETED SUCCESSFULLY")
        logger.info(f"Duration: {duration:.2f} seconds")
        logger.info("#" * 70)

    except KeyboardInterrupt:

        logger.error(
            "Pipeline cancelled by user."
        )

        raise

    except Exception as error:

        completed_at = utc_now()

        duration = time.time() - start_time

        status = create_pipeline_status(
            status="failed",
            started_at=pipeline_start,
            completed_at=completed_at,
            failed_stage=current_stage,
            error=str(error)
        )

        save_pipeline_status(status)

        logger.error("")
        logger.error("#" * 70)
        logger.error("PIPELINE FAILED")
        logger.error(f"Stage: {current_stage}")
        logger.error(f"Error: {error}")
        logger.error(f"Duration: {duration:.2f} seconds")
        logger.error("#" * 70)

        raise


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":

    try:

        run_pipeline()

    except KeyboardInterrupt:

        sys.exit(130)

    except Exception:

        sys.exit(1)